name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
load: startup
softdepend:
    - PermissionsEx
    - PermissionsBukkit
    - bPermissions
    - EssentialsGroupManager
    - zPermissions
    - Vault
    - Permissions
    - Multiverse-Core
commands:
  dm:
    description: Dungeon Maze command
    usage: /dm
  dungeonmaze:
    description: Dungeon Maze command
    usage: /dungeonmaze
