name: DungeonMaze
main: com.timvisee.dungeonmaze.DungeonMaze
version: ${project.version}
load: startup
softdepend: [Multiverse-Core, Vault, PermissionsBukkit, Permissions, PermissionsEX, EssentialsGroupManager]
commands:
  dm:
    description: Dungeon Maze command
    usage: /dm
  dungeonmaze:
    description: Dungeon Maze command
    usage: /dungeonmaze
